{"name": "Order creation without ingredients but with auth error test", "status": "passed", "start": 1727809266548, "stop": 1727809267208, "uuid": "d8f36cbf-ff16-4c56-983b-3151a3d9dd0c", "historyId": "10732fc5e19da7c4ffd9b151d7ba5684", "testCaseId": "10732fc5e19da7c4ffd9b151d7ba5684", "fullName": "tests.test_create_order.TestCreateOrder#test_create_order_no_ingredients_with_auth", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_order"}, {"name": "subSuite", "value": "TestCreateOrder"}, {"name": "host", "value": "WIN-B95O9QQ3RDO"}, {"name": "thread", "value": "23340-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_order"}]}